version: "3"
services:
  api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - redis
      - postgis
    ports:
      - 9050:9050
    command: yarn start:dev

  redis:
    image: redis:alpine

  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=kango_admin
      - POSTGRES_PASSWORD=kango_password_of_life
      - POSTGRES_DB=kango